name: Publish Release

on:
  push:
    tags:
      - '*GA'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run build script
        run: ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/utils.sh